server:
  port: 8080

spring:
  application:
    name: weather-service

eureka:
  instance:
    hostname: localhost

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  author: Tulio L. Viglione
  mail: tulio.l.viglione@gmail.com
  celular: (xx)xxxx-xxxx
